- name: Clean Up Report File
  hosts: localhost
  connection: local
  serial: 10

  vars:
    # path where reports will be stored
    csv_path: reports
    report_file_name: 'panos_installed_os_audit_{{ansible_date_time.date}}.csv'

    # CSV Headers for Reporting
    headers: >-
      Store_Number,Installed_OS,Target_OS,UptimeFW1,HA_Active_IP,HA_Active_Status,UptimeFW2,HA_Passive_IP,HA_Passive_Status,BGP_State

  tasks:
    - name: Generate Report File Name
      ansible.builtin.set_fact:
        csv_filename: 'panos_installed_os_audit_{{ansible_date_time.date}}.csv'
      delegate_to: localhost

    - ansible.builtin.include_tasks: tasks/upgrade_report_file.yml


- name: Gather PANOS Installed OS Info
  hosts: all
  connection: local
  serial: 10

  vars:
    primary:
      ip_address: '{{ primary_ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    secondary:
      ip_address: '{{ secondary_ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    # CSV Headers for Reporting
    headers: >-
      Store_Number,Installed_OS,Target_OS,UptimeFW1,HA_Active_IP,HA_Active_Status,UptimeFW2,HA_Passive_IP,HA_Passive_Status,BGP_State

    # path where reports will be stored
    csv_path: reports
    report_file_name: 'panos_installed_os_audit_{{ansible_date_time.date}}.csv'


  tasks:
    - name: Generate Report File Name
      ansible.builtin.set_fact:
        csv_filename: 'panos_installed_os_audit_{{ansible_date_time.date}}.csv'
      delegate_to: localhost

    - ansible.builtin.include_tasks: tasks/panos_roles_in_ha.yml

    - name: Saving Previous Image OS version Info
      ansible.builtin.set_fact:
        pre_os_version: "{{ os_version }}"

    - ansible.builtin.include_tasks: tasks/check_bgp_status.yml

    - name: Build Out CSV File
      ansible.builtin.lineinfile:
        path: "{{ csv_path }}/{{ csv_filename }}"
        line: >-
          {{inventory_hostname}},{{pre_os_version}},{{version}},{{fw1_uptime}},{{primary_ip_address}},{{primary_ha}}
          ,{{fw2_uptime}},{{secondary_ip_address}},{{secondary_ha}},{{peer_status}}
        state: present
        create: true
        insertafter: EOF
      delegate_to: localhost
      throttle: 1

- name: Send Email Report
  hosts: localhost
  vars:
    csv_path: reports
    headers: >-
      Store_Number,Installed_OS,Target_OS,UptimeFW1,HA_Active_IP,HA_Active_Status,UptimeFW2,HA_Passive_IP,HA_Passive_Status,BGP_State

  tasks:
    - name: Generate Report File Name
      ansible.builtin.set_fact:
        csv_filename: 'panos_installed_os_audit_{{ansible_date_time.date}}.csv'
      delegate_to: localhost

    - name: Read in CSV to Variable
      community.general.read_csv:
        path: "{{ csv_path }}/{{ csv_filename }}"
      register: csv_file
      delegate_to: localhost
      run_once: true

    - name: Send Email
      community.general.mail:
        host: "{{ email_host }}"
        from: "{{ email_from }}"
        port: 25
        to: "{{ email_to }}"
        subject: "[Ansible] PANOS Installed Audit - {{ansible_date_time.date}}"
        body: "{{ lookup('template', 'panos_audit_report_template.html.j2') }}"
        attach: "{{ csv_path }}/{{ csv_filename }}"
        subtype: html
        secure: never
      delegate_to: localhost
      run_once: true
